version: '2.4'
services:

  dev-memo:
    image: node:20-alpine
    working_dir: /home/app
    ports: 
      - 3000:3000
    volumes:
      - ./app:/home/app
    command:
      - /bin/sh
      - -c
      - |
        npm install
        npm run start